version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfiles/Dockerfile-app
      context: .
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - celery-worker
      - redis

  celery-worker:
    build:
      dockerfile: Dockerfiles/Dockerfile-celery
      context: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    tty: true
    depends_on:
      - redis

  redis:
    image:
      "redis:7-alpine"
    ports:
      - "127.0.0.1:6379:6379"
