FROM python:3.11-alpine AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --prefix=/install -r requirements.txt

FROM python:3.11-alpine

WORKDIR /app

COPY --from=builder /install /usr/local/

COPY script script

COPY app app

RUN find script -type f -exec chmod +x {} \;

CMD ["/app/script/docker-entrypoint.sh"]

